### ISSUE TITLE
Gnome shell crashes when repeatedly moving window to last workspace

### ISSUE THREAD

**Issue by arngo** [carmanaught/gnome-shell-extension-workspace-buttons#1]
Gnome 3.26.1 running on Arch Linux

With dynamic workspaces enabled, an empty workspace is created at the end of all non-empty workspaces. Moving a window to the empty workspace at the end and repeating this with the newly created workspace one or more times will cause gnome shell to crash.

The following appears in `journalctl /usr/bin/gnome-shell`

    JS ERROR: TypeError: metaWorkspace is null
                                         _updateLabel/<@/home/arnold/.local/share/gnome-shell/extensions/workspace-buttons@carmanaught.github.com/extension.js:457:17
    JS ERROR: TypeError: metaWorkspace is null
                                         _updateStyle/<@/home/arnold/.local/share/gnome-shell/extensions/workspace-buttons@carmanaught.github.com/extension.js:388:17
    JS ERROR: TypeError: metaWorkspace is null
                                         _updateMenu/<@/home/arnold/.local/share/gnome-shell/extensions/workspace-buttons@carmanaught.github.com/extension.js:323:17

**Comment by carmanaught** [comment]
I use static workspaces, so haven't run into the issue previously but I've just been testing this and can reproduce the shell crash and the errors (I managed to have my shell crash back to GDM even!).

I think some of this may be to do with the creating/destruction of the buttons, but I'm still figuring out what the issues are. To avoid crashes until this I can figure out how to fix this and if you want to keep using this extension, I'd suggest using static workspaces for now.

**Comment by carmanaught** [comment]
This was indeed related to the creation/destruction of buttons and I believe it's fixed now. Please update and check to see if it's working now.

**Comment by arngo** [comment]
It's working great now. Thank you!
